/**
 * HTTP RPC demo
 * Exposing RPCOps interfaces as webservices
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import io.swagger.client.models.StateMachineRunId

import io.swagger.client.infrastructure.*

class FlowManagerRPCOpsApi(basePath: kotlin.String = "/api/v1") : ApiClient(basePath) {

    /**
     * 
     * 
     * @return void
     */
    fun getFlowmanagerrpcopsDebugcheckpoints(): Unit {
        
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/flowmanagerrpcops/debugcheckpoints"
        )
        val response = request<Any?>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @return void
     */
    fun getFlowmanagerrpcopsDumpcheckpoints(): Unit {
        
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/flowmanagerrpcops/dumpcheckpoints"
        )
        val response = request<Any?>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @return kotlin.Int
     */
    @Suppress("UNCHECKED_CAST")
    fun getFlowmanagerrpcopsGetprotocolversion(): kotlin.Int {
        
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/flowmanagerrpcops/getprotocolversion"
        )
        val response = request<kotlin.Int>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Int
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @return kotlin.collections.Map<kotlin.String, StateMachineRunId>
     */
    @Suppress("UNCHECKED_CAST")
    fun getFlowmanagerrpcopsListactive(): kotlin.collections.Map<kotlin.String, StateMachineRunId> {
        
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/flowmanagerrpcops/listactive"
        )
        val response = request<kotlin.collections.Map<kotlin.String, StateMachineRunId>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.collections.Map<kotlin.String, StateMachineRunId>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param runid Run ID for a previously started flow 
     * @return kotlin.Boolean
     */
    @Suppress("UNCHECKED_CAST")
    fun postFlowmanagerrpcopsKillflowRunid(runid: kotlin.String): kotlin.Boolean {
        
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/flowmanagerrpcops/killflow/{runid}".replace("{" + "runid" + "}", "$runid")
        )
        val response = request<kotlin.Boolean>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Boolean
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
