/**
 * HTTP RPC demo
 * Exposing RPCOps interfaces as webservices
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param commonName 
 * @param country 
 * @param locality 
 * @param organisation 
 * @param organisationUnit 
 * @param state 
 * @param x500Principal 
 */
data class CordaX500Name (

    val commonName: kotlin.String? = null,
    val country: kotlin.String,
    val locality: kotlin.String,
    val organisation: kotlin.String,
    val organisationUnit: kotlin.String? = null,
    val state: kotlin.String? = null,
    val x500Principal: kotlin.String
) {
}