/**
 * HTTP RPC demo
 * Exposing RPCOps interfaces as webservices
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param awaitForResultTimeout 
 * @param currentPosition 
 * @param maxCount 
 */
data class DurableStreamContext (

    val awaitForResultTimeout: kotlin.String,
    val currentPosition: kotlin.Long,
    val maxCount: kotlin.Int
) {
}