/**
 * HTTP RPC demo
 * Exposing RPCOps interfaces as webservices
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ExceptionDigest

/**
 * 
 * @param exceptionDigest 
 * @param resultJson 
 * @param status 
 */
data class RpcFlowOutcomeResponse (

    val exceptionDigest: ExceptionDigest,
    val resultJson: kotlin.String? = null,
    val status: kotlin.String
) {
}