/**
 * HTTP RPC demo
 * Exposing RPCOps interfaces as webservices
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.RpcNamedQueryParameterJson

/**
 * Request object containing information to execute a pre-defined named query
 * @param namedParameters 
 * @param postProcessorName 
 * @param queryName 
 */
data class RpcNamedQueryRequest (

    val namedParameters: kotlin.collections.Map<kotlin.String, RpcNamedQueryParameterJson>,
    val postProcessorName: kotlin.String? = null,
    val queryName: kotlin.String
) {
}