/**
 * HTTP RPC demo
 * Exposing RPCOps interfaces as webservices
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.RpcCorDappInfo

/**
 * 
 * @param corDapps 
 * @param platformVersion 
 * @param revision 
 * @param vendor 
 * @param version 
 */
data class RpcNodeDiagnosticInfo (

    val corDapps: kotlin.Array<RpcCorDappInfo>,
    val platformVersion: kotlin.Int,
    val revision: kotlin.String,
    val vendor: kotlin.String,
    val version: kotlin.String
) {
}