/**
 * HTTP RPC demo
 * Exposing RPCOps interfaces as webservices
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * Simple filter to retrieve vault state identifiers
 * @param contractStateClassNames 
 * @param endTimestamp 
 * @param eventTypes 
 * @param relevancyStatuses 
 * @param startTimestamp 
 * @param stateStatuses 
 * @param txIds 
 */
data class RpcVaultQueryFilterRequest (

    val contractStateClassNames: kotlin.Array<kotlin.String>? = null,
    val endTimestamp: kotlin.String? = null,
    val eventTypes: kotlin.Array<kotlin.String>? = null,
    val relevancyStatuses: kotlin.Array<kotlin.String>? = null,
    val startTimestamp: kotlin.String? = null,
    val stateStatuses: kotlin.Array<kotlin.String>? = null,
    val txIds: kotlin.Array<kotlin.String>? = null
) {
}