/**
 * HTTP RPC demo
 * Exposing RPCOps interfaces as webservices
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.CordaX500Name
import io.swagger.client.models.StateRef

/**
 * 
 * @param contractStateClassName 
 * @param eventTimestamp 
 * @param notary 
 * @param ref 
 * @param relevancyStatus 
 * @param stateStatus 
 * @param status 
 */
data class RpcVaultStateResponseItem (

    val contractStateClassName: kotlin.String,
    val eventTimestamp: kotlin.String,
    val notary: CordaX500Name,
    val ref: StateRef,
    val relevancyStatus: kotlin.String,
    val stateStatus: kotlin.String,
    val status: kotlin.String
) {
}