/**
 * HTTP RPC demo
 * Exposing RPCOps interfaces as webservices
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ByteArray

/**
 * 
 * @param bytes 
 * @param offset 
 * @param size 
 */
data class SecureHash (

    val bytes: ByteArray,
    val offset: kotlin.Int,
    val size: kotlin.Int
) {
}